import com.badlogic.gdx.math.Interpolation;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Admin' at '11/21/16 3:22 PM' with Gradle 3.0
 *
 * @author Admin, @date 11/21/16 3:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
    	
        return true;
    }
}
